[persistance]
source_dir = "data"
persist_dir = "./storage"

[chunking]
hf_embedding_model_name = "BAAI/bge-base-en-v1.5"
chunk_size = 512
chunk_overlap = 20

[retrieval]
similarity_top_k=3

[ollama]
llm = "phi3"