[persistance]
source_dir = "data"

[chunking]
hf_embedding_model_name = "BAAI/bge-base-en-v1.5"
chunk_size = 512
chunk_overlap = 20

[retrieval]
similarity_top_k=3
sparse_top_k=5

[openai]
azure_deployment="starschema-gpt4o"
api_version="2024-05-01-preview"
model="gpt-4o"

# [ollama]
# llm = "phi3"

# this is likely not available, change it to running qdrant IP
[qdrant]
url="http://20.13.43.101"
port=6333
collection_name="hybrid_collection"